[databaseConfig]
database = "social_media_database"
user = "social_media_user"
password = "dummypassword"
host = "localhost"
port = 3306

[sentimentEndpointSecConfig]
endpointUrl = "http://localhost:9098/text-processing"
retryInterval = 3.0

[ballerina.observe]
metricsEnabled=true
metricsReporter="prometheus"
tracingEnabled=true
tracingProvider="jaeger"

